# Generated by Django 5.1 on 2024-10-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course',
            field=models.CharField(choices=[('AOOP', 'Advance Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('DBMS', 'Database Management Systems'), ('DSA', 'Data Structures and Algorithms'), ('AI', 'Artificial Intelligence')], max_length=50),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='section',
            field=models.CharField(choices=[('S1', 'Section S1'), ('S2', 'Section S2'), ('S3', 'Section S3'), ('S4', 'Section S4'), ('S5', 'Section S5'), ('S6', 'Section S6'), ('S7', 'Section S7'), ('S8', 'Section S8'), ('S9', 'Section S9')], max_length=5),
        ),
        migrations.AlterField(
            model_name='marks',
            name='course',
            field=models.CharField(choices=[('AOOP', 'ADVANCE Object-Oriented Programming'), ('PFSD', 'Python Full Stack Developement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
