# Generated by Django 5.1 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_feedback_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='text_field',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='textfield',
            field=models.TextField(default='No comments provided', max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
